feat: Support Casbin UpdatableAdapter interface
php-casbin/yii-permission pull request #15
Opened 2021-09-23 02:10 UTC by basakest

2021-09-23 04:46 UTC, hsluoyz commented
@techoner plz review

2021-09-23 15:39 UTC, leeqvip requested changes

2021-09-23 15:39 UTC, techoner commented on src/Adapter.php
> +            });
@basakest For filtering rules, please refer to: https://github.com/php-casbin/dbal-adapter/blob/master/src/Adapter.php#L435

2021-09-25 14:20 UTC, techoner requested changes

2021-09-25 14:20 UTC, techoner commented on src/Adapter.php
> +            $transaction->rollBack();
@basakest  The exception should not be ignored here, same as updatePolicies().

2021-09-26 15:49 UTC, techoner approved these changes

2021-09-26 15:50 UTC, merged

2021-09-26 15:52 UTC, techoner commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/yii-permission/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: