perf: updated version of phpunit and fixed workflow issues
php-casbin/yii-permission pull request #17
Opened 2024-05-25 08:59 UTC by Dobmod

Replaced the old Travis CI badge with GitHub Actions CI badge in README.md, and all unit tests in the workflow were all green, but I am unable to test the issues that occurred on the 'release'.😁

2024-05-25 10:07 UTC, leeqvip requested changes
Please update the node version for github actions

2024-05-26 03:05 UTC, leeqvip commented on composer.json
> +            "yiisoft/yii2-composer": true
Is this necessary ?

2024-05-26 03:33 UTC, Dobmod commented on composer.json
> +            "yiisoft/yii2-composer": true
Yeah, I have tested it. 
If not, during the 'composer install' process, a confirmation option about `yii2-composer` installation appears,and the workflow will be red. 😯

2024-05-26 04:06 UTC, leeqvip approved these changes

2024-05-26 04:14 UTC, merged

2024-05-26 04:16 UTC, leeqvip commented
:tada: This PR is included in version 1.5.1 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/yii-permission/releases/tag/v1.5.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: